controller_list:
  - name: fake_right_hand_controller
    joints:
      - right_hand_Thumb_Opposition
      - right_hand_Thumb_Flexion
      - right_hand_Index_Finger_Proximal
      - right_hand_Index_Finger_Distal
      - right_hand_Middle_Finger_Proximal
      - right_hand_Middle_Finger_Distal
      - right_hand_Finger_Spread
      - right_hand_Pinky
      - right_hand_Ring_Finger